export const VCT_REGIONS = [
  { id: "americas", name: "Americas", color: "bg-red-500" },
  { id: "emea", name: "EMEA", color: "bg-blue-500" },
  { id: "pacific", name: "Pacific", color: "bg-yellow-500" },
  { id: "cn", name: "CN", color: "bg-purple-500" },
] as const;

export const VALORANT_MAPS = [
  "Ascent",
  "Bind",
  "Haven",
  "Lotus",
  "Sunset",
  "Abyss",
  "Corrode",
  "Split",
  "Pearl",
  "Fracture",
  "Icebox",
  "Breeze",
] as const;

export const VCT_TEAMS = {
  americas: [
    "Sentinels",
    "LOUD",
    "Evil Geniuses",
    "NRG",
    "Leviatán",
    "100 Thieves",
    "Cloud9",
    "FURIA",
    "G2 Esports",
    "KRÜ Esports",
    "MIBR",
  ],
  emea: [
    "Fnatic",
    "Team Liquid",
    "Natus Vincere",
    "Team Vitality",
    "Karmine Corp",
    "BBL Esports",
    "Team Heretics",
    "GIANTX",
    "KOI",
    "Gentle Mates",
  ],
  pacific: [
    "Paper Rex",
    "DRX",
    "Gen.G",
    "T1",
    "ZETA DIVISION",
    "Team Secret",
    "Rex Regum Qeon",
    "Global Esports",
    "Talon Esports",
    "DetonatioN FocusMe",
    "Bleed Esports",
  ],
  cn: [
    "EDward Gaming",
    "Bilibili Gaming",
    "FunPlus Phoenix",
    "Titan Esports Club",
    "Trace Esports",
    "JD Gaming",
    "Wolves Esports",
    "All Gamers",
    "Dragon Ranger Gaming",
    "Nova Esports",
  ],
} as const;

export const MOCK_SEARCH_RESULTS = [
  {
    id: "match-1",
    team_a: "Sentinels",
    team_b: "LOUD",
    score_a: 13,
    score_b: 11,
    map_name: "Ascent",
    round_count: 24,
    tournament: "VCT Americas 2024",
    date: "2024-04-20",
    summary: "Sentinels successfully retook A site 4 times this match using a Sova/KAYO reveal combo.",
    vod_timestamp: 450,
    tags: ["Retake", "Defense", "Win"],
  },
  {
    id: "match-2",
    team_a: "Paper Rex",
    team_b: "DRX",
    score_a: 13,
    score_b: 5,
    map_name: "Lotus",
    round_count: 18,
    tournament: "VCT Pacific 2024",
    date: "2024-05-12",
    summary: "PRX displayed aggressive C mound control, stifling DRX's default executes.",
    vod_timestamp: 120,
    tags: ["Aggression", "Defense", "Flawless"],
  },
  {
    id: "match-3",
    team_a: "Fnatic",
    team_b: "Team Liquid",
    score_a: 14,
    score_b: 12,
    map_name: "Bind",
    round_count: 26,
    tournament: "VCT EMEA 2024",
    date: "2024-03-15",
    summary: "Boaster's clutch in Round 24 secured the overtime opportunity.",
    vod_timestamp: 2800,
    tags: ["Clutch", "Overtime", "Thriller"],
  },
];
